### PR TITLE
More robust

### PR DESCRIPTION
**Pull request by Teun**
Main improvements are around usability of the UI. UI in these applications are logfiles and command line interface.
- Added the Args library to implement command line switches and make the app self describing with a usage/help option
- Used log4net for writing to 3 destinations: console in colors, a tech log for admins and a functional log that can be sent to investigators, containing an error comment and the actual values from the csv
- Using BatchFlow (sorry, couldn't resist) I implemented retry logic around the webservice call and resume logic. Note how the log will explain how to resume.

### CODE REVIEW

**Comment by emilebosch** [comment]
Hey thanks for your pul request, i'll go and see if i can build your PR. I'll review it later today.

On Dec 19, 2012, at 12:59 PM, Teun notifications@github.com wrote:

Main improvements are around usability of the UI. UI in these applications are logfiles and command line interface.
Added the Args library to implement command line switches and make the app self describing with a usage/help option
Used log4net for writing to 3 destinations: console in colors, a tech log for admins and a functional log that can be sent to investigators, containing an error comment and the actual values from the csv
Using BatchFlow (sorry, couldn't resist) I implemented retry logic around the webservice call and resume logic. Note how the log will explain how to resume.
You can merge this Pull Request by running:

  git pull https://github.com/Teun/codeassignment1 teunssolution
Or view, comment on, or merge it at:
  https://github.com/emilebosch/codeassignment1/pull/7
Commit Summary

BatchFlow introduced. Added Args for command line options.
improved descriptions on command line switches
Merge branch 'master' of https://github.com/emilebosch/codeassignment1 …
File Changes

M OVImport.suo (0)
M OVImport/App.config (68)
A OVImport/Arguments.cs (40)
M OVImport/Data/sample.csv (1)
M OVImport/Lib/OVTransactionImport.cs (189)
A OVImport/Lib/ProblemReportData.cs (13)
M OVImport/Lib/SimpleRest.cs (2)
M OVImport/OVImport.csproj (14)
M OVImport/OVImport.csproj.user (3)
M OVImport/Program.cs (61)
M OVImport/packages.config (3)
M OVTransactionWebservice/Controllers/OVTransactionImportController.cs (23)
Patch Links

https://github.com/emilebosch/codeassignment1/pull/7.patch
https://github.com/emilebosch/codeassignment1/pull/7.diff

**Comment by emilebosch** [comment]
HI! i've run your code! Kudos for logging and console output, both very handy.
However, did i miss something or does it bail on the first proper exception? It gives me the option to skipuntil but wouldnt it be better if it retried anyway, put the failed things away in a 'failed' log and gives u the possibility to retry those again?

Thanks!

**Comment by Teun** [comment]
Did you check the usage output? It specifies a retry switch that has a
default value of zero. If you pass 2, you should normally not fall on
chance exceptions.
 Op 16 jan. 2013 23:55 schreef "Emile Bosch" notifications@github.com het
volgende:

**Comment by emilebosch** [comment]
Hi! Thanks well further imrovements could be:
- Save the failed items in a log and make it possible to retry them (or use diminishing sets)
- Log the arguments so we can see what the user typed in

**Pull request closed without merging**
